name: Construir imagen y subirla a DockerHub

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Login en Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Preparar construccion con Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Construir imagen y subirla a DockerHub
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/docker-github-actions:latest
                  ${{ secrets.DOCKERHUB_USERNAME }}/docker-github-actions:${{ github.sha }}
